name: Nightly Test

on:
  schedule:
    - cron: '15 3 * * *'

env:
  COLORTERM: 'yes'
  TERM: 'xterm-256color'
  PYTEST_ADDOPTS: '--color=yes'
  CONTAINER_RUNTIME: 'docker'

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: "3.11"
            image_tag: "nightly"
            pulp_api_root: "/relocated/djnd/"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install Test Dependencies
        run: |
          if [ "${{matrix.click_version}}" ]
          then
            pip install -r test_requirements.txt click~=${{ matrix.click_version }}
          else
            pip install -r test_requirements.txt
          fi
      - name: Run tests
        env:
          CONTAINER_RUNTIME: ${{ matrix.container_runtime }}
          IMAGE_TAG: ${{ matrix.image_tag }}
          FROM_TAG: ${{ matrix.from_tag }}
          CONTAINER_FILE: ${{ matrix.container_file }}
          PULP_API_ROOT: ${{ matrix.pulp_api_root }}
        run: .ci/run_container.sh make test
